<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $subject }}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; color: #1f2937; line-height: 1.5; padding: 24px;">
    <h2 style="margin: 0 0 12px 0; color: #111827;">{{ $subject }}</h2>
    <p style="margin: 0 0 16px 0; font-size: 14px; color: #6b7280;">
        <strong>Trigger:</strong> {{ $triggerLabel }} &middot;
        <strong>Fired at:</strong> {{ $triggeredAt->format('Y-m-d H:i:s T') }}
    </p>
    <p style="margin: 0 0 16px 0;">{{ $body }}</p>

    @if(! empty($context))
        <table style="border-collapse: collapse; margin-top: 8px;">
            @foreach($context as $key => $value)
                <tr>
                    <td style="padding: 4px 12px 4px 0; color: #6b7280; font-size: 13px; text-transform: uppercase;">
                        {{ $key }}
                    </td>
                    <td style="padding: 4px 0; font-family: monospace; font-size: 13px;">
                        {{ is_scalar($value) ? $value : json_encode($value) }}
                    </td>
                </tr>
            @endforeach
        </table>
    @endif

    <p style="margin: 24px 0 0 0; font-size: 12px; color: #9ca3af;">
        This alert was generated by jobs-monitor. To adjust thresholds or channels, edit your <code>config/jobs-monitor.php</code>.
    </p>
</body>
</html>
